;======================================
;------- Hardware Script Output -------
;======================================
;To customize or restore defaults click on any of the Izzern Gauge Icons (CPU, GPU, RAM, etc.).

[Variables]
CPUName=AMD Ryzen 9 5900X 12-Core Processor
CPUSpeed=3701
EthernetName=Intel(R) I211 Gigabit Network Connection
EthernetIP=192.168.1.41
EthernetConn=Connected
EthernetDns=192.168.1.1
GPUName=NVIDIA GeForce GTX 1060 6GB
GPU1Name=N/A
GPU2Name=N/A
GPU3Name=N/A
RAMCap=34359738368
RAMMan=Corsair
RAMModel=Vengeance Pro RGB
RAMSpeed=3200
TotalRAM=32
VRAM=6
VRAM1=6
VRAM2=N/A
VRAM3=N/A
WifiName=Intel(R) Dual Band Wireless-AC 3168
WifiIP=169.254.156.252
WifiConn=Disconnected
WifiDns=8.8.8.8  |  8.8.4.4
Path=MSIA Dashboard Gauges Master
