;=================================================================
;-------------------- Variables Config File ----------------------
;=================================================================
;To customize or restore defaults click on any of the Izzern Honeycomb Icons (CPU, GPU, or RAM).

[Variables]
;======================================
;---------- Position & Scale ----------
;======================================
Scale=1.0

;Text Offset
TextX=29
TextY=23.5

FontFaceFPS=Segoe UI

;======================================
;--------------- Colors ---------------
;======================================
PercentLevel1=0,245,212
PercentLevel2=0,187,249
PercentLevel3=155,93,229
PercentLevel4=241,91,181

BGColor=255,255,255
GearTint=155,155,155
IconColor=255,0,0
BorderColorFPS=0,0,0

;======================================
;------------- Text Styles ------------
;======================================
FontSizeFPS=16
FontSizeFPS2=22
