[Variables]
;=================================================================
;---------------------------- System -----------------------------
;=================================================================
ScaleVis=1
Bands=26
FreqMin=300
FreqMax=13000
GainUser=5
Selection=Spectrum
BGImage=D:\OneDrive\Documents\Rainmeter\Skins\MSIA Dashboard Gauges Master\@Resources\Visualizer\Images\radio-volume-gradient.png

;=================================================================
;---------------------------- Styles -----------------------------
;=================================================================
AlphaUser=50

BarColor=50,0,255
BarWidth=12
BarHeight=120
BarSpacingX=2

BGColor=50,50,50,#Alpha#

;-------------------------- Reflection ---------------------------
Reflection=1
PercentBottom=80
