[Variables]
;@includeVariablesVisualizer=#@#Visualizer\Settings\VariablesVisualizer.inc
;@includeMeasures=#@#Visualizer\Settings\Analyzer.inc

[MeasureBand1]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=0
HandlerName=MainFinalOutput

[MeasureBand2]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=1
HandlerName=MainFinalOutput
Disabled=(#Bands# < 2)

[MeasureBand3]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=2
HandlerName=MainFinalOutput
Disabled=(#Bands# < 3)

[MeasureBand4]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=3
HandlerName=MainFinalOutput
Disabled=(#Bands# < 4)

[MeasureBand5]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=4
HandlerName=MainFinalOutput
Disabled=(#Bands# < 5)

[MeasureBand6]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=5
HandlerName=MainFinalOutput
Disabled=(#Bands# < 6)

[MeasureBand7]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=6
HandlerName=MainFinalOutput
Disabled=(#Bands# < 7)

[MeasureBand8]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=7
HandlerName=MainFinalOutput
Disabled=(#Bands# < 8)

[MeasureBand9]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=8
HandlerName=MainFinalOutput
Disabled=(#Bands# < 9)

[MeasureBand10]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=9
HandlerName=MainFinalOutput
Disabled=(#Bands# < 10)

[MeasureBand10]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=9
HandlerName=MainFinalOutput
Disabled=(#Bands# < 10)

[MeasureBand11]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=10
HandlerName=MainFinalOutput
Disabled=(#Bands# < 11)

[MeasureBand12]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=11
HandlerName=MainFinalOutput
Disabled=(#Bands# < 12)

[MeasureBand13]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=12
HandlerName=MainFinalOutput
Disabled=(#Bands# < 13)

[MeasureBand14]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=13
HandlerName=MainFinalOutput
Disabled=(#Bands# < 14)

[MeasureBand15]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=14
HandlerName=MainFinalOutput
Disabled=(#Bands# < 15)

[MeasureBand16]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=15
HandlerName=MainFinalOutput
Disabled=(#Bands# < 16)

[MeasureBand17]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=16
HandlerName=MainFinalOutput
Disabled=(#Bands# < 17)

[MeasureBand18]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=17
HandlerName=MainFinalOutput
Disabled=(#Bands# < 18)

[MeasureBand19]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=18
HandlerName=MainFinalOutput
Disabled=(#Bands# < 19)

[MeasureBand20]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=19
HandlerName=MainFinalOutput
Disabled=(#Bands# < 20)

[MeasureBand21]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=20
HandlerName=MainFinalOutput
Disabled=(#Bands# < 21)

[MeasureBand22]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=21
HandlerName=MainFinalOutput
Disabled=(#Bands# < 22)

[MeasureBand23]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=22
HandlerName=MainFinalOutput
Disabled=(#Bands# < 23)

[MeasureBand24]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=23
HandlerName=MainFinalOutput
Disabled=(#Bands# < 24)

[MeasureBand25]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=24
HandlerName=MainFinalOutput
Disabled=(#Bands# < 25)

[MeasureBand26]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=25
HandlerName=MainFinalOutput
Disabled=(#Bands# < 26)

[MeasureBand27]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=26
HandlerName=MainFinalOutput
Disabled=(#Bands# < 27)

[MeasureBand28]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=27
HandlerName=MainFinalOutput
Disabled=(#Bands# < 28)

[MeasureBand29]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=28
HandlerName=MainFinalOutput
Disabled=(#Bands# < 29)

[MeasureBand30]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=29
HandlerName=MainFinalOutput
Disabled=(#Bands# < 30)

[MeasureBand31]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=30
HandlerName=MainFinalOutput
Disabled=(#Bands# < 31)

[MeasureBand32]
Measure=Plugin
Plugin=AudioAnalyzer
Type=Child
Parent=Analyzer
Channel=Auto
Index=31
HandlerName=MainFinalOutput
Disabled=(#Bands# < 32)